# Generated by Django 4.2.7 on 2023-12-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_email_body_alter_email_recipiend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uniq_token',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
