# Generated by Django 4.2.7 on 2023-12-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_uniq_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='send_date',
            field=models.CharField(),
        ),
    ]
